version: '3'
services:
    api:
        build: .
        volumes:
          - .:/code
        command: python3 recipes/server.py
        env_file: docker.env
        links:
            - postgres
        ports:
          - "8080:8080"

    postgres:
        image: postgres:10
        ports:
            - "5432:5432"
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: hellofresh
            POSTGRES_PASSWORD: hellofresh
            POSTGRES_DB: hellofresh
